version: '3.4'
services:
  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - C:\Users\Playdata\redis_volume\redis.conf:/usr/local/etc/redis/redis.conf
      - C:\Users\Playdata\redis_volume\data:/data
    restart: always
    sysctls:
      - vm.overcommit_memory=1
  springboot:
    image: openjdk:17-alpine
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 1234
    depends_on:
      - redis